export const GET_TUTORIAL = "GET_TUTORIAL";
export const OPEN_TUTORIAL_DIALOG = "OPEN_TUTORIAL_DIALOG";
export const CLOSE_TUTORIAL_DIALOG = "CLOSE_TUTORIAL_DIALOG";
export const ADD_NEW_TUTORIAL = "ADD_NEW_TUTORIAL";
export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
export const DELETE_TUTORIAL = "DELETE_TUTORIAL";
