export const GET_BOOKING = "GET_BOOKING";
export const DELETE_BOOKING = "DELETE_BOOKING";
export const OPEN_BOOKING_DIALOG = "OPEN_BOOKING_DIALOG";
export const CLOSE_BOOKING_DIALOG = "CLOSE_BOOKING_DIALOG";

export const OPEN_STAFF_ASSIGN_DIALOG = "OPEN_STAFF_ASSIGN_DIALOG";
export const CLOSE_STAFF_ASSIGN_DIALOG = "CLOSE_STAFF_ASSIGN_DIALOG";
export const ASSIGN_STAFF = "ASSIGN_STAFF";

export const OPEN_VENDOR_ASSIGN_DIALOG = "OPEN_VENDOR_ASSIGN_DIALOG";
export const CLOSE_VENDOR_ASSIGN_DIALOG = "CLOSE_VENDOR_ASSIGN_DIALOG";
export const ASSIGN_VENDOR = "ASSIGN_VENDOR";
