export const GET_CATEGORY = "GET_CATEGORY";
export const OPEN_CATEGORY_DIALOG = "OPEN_CATEGORY_DIALOG";
export const CLOSE_CATEGORY_DIALOG = "CLOSE_CATEGORY_DIALOG";
export const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
