export const GET_SERVICE = "GET_SERVICE";
export const OPEN_SERVICE_DIALOG = "OPEN_SERVICE_DIALOG";
export const CLOSE_SERVICE_DIALOG = "CLOSE_SERVICE_DIALOG";
export const ADD_NEW_SERVICE = "ADD_NEW_SERVICE";
export const UPDATE_SERVICE = "UPDATE_SERVICE";
export const DELETE_SERVICE = "DELETE_SERVICE";
