export const GET_SERVICE = "GET_SERVICE";
export const OPEN_SERVICE_DIALOG = "OPEN_SERVICE_DIALOG";
export const CLOSE_SERVICE_DIALOG = "CLOSE_SERVICE_DIALOG";
export const ADD_NEW_SERVICE = "ADD_NEW_SERVICE";
export const UPDATE_SERVICE = "UPDATE_SERVICE";
export const DELETE_SERVICE = "DELETE_SERVICE";
export const TOGGLE_SHOW = "TOGGLE_SHOW";
// Edit or Create-New
export const UPDATE_SERVICE_DETAILS = "UPDATE_SERVICE_DETAILS";
export const CLEAR_SERVICE_DETAILS = "CLEAR_SERVICE_DETAILS";
