export const GET_VIDEO = "GET_VIDEO";
export const OPEN_VIDEO_DIALOG = "OPEN_VIDEO_DIALOG";
export const CLOSE_VIDEO_DIALOG = "CLOSE_VIDEO_DIALOG";
export const ADD_NEW_VIDEO = "ADD_NEW_VIDEO";
export const UPDATE_VIDEO = "UPDATE_VIDEO";
export const DELETE_VIDEO = "DELETE_VIDEO";
